steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'ENV_FILE=$_ENV_FILE',
        '--build-arg',
        'PORT=$_PORT',
        '--build-arg',
        'ENV=$_ENV',
        '-t',
        'gcr.io/project/battledak-server-$_ENV',
        '.',
      ]
images:
  - 'gcr.io/project/battledak-server-$_ENV'
substitutions:
  _ENV_FILE: '.env'
  _ENV: 'prod'
  _PORT: '8080'
