steps:
  # Create .env file from Secret Manager or use empty one
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$_ENV_FILE" != "" ]; then
          # Try to get from Secret Manager if specified
          gcloud secrets versions access latest --secret="gateway-dashboard-front-$_ENV" > .env 2>/dev/null || echo "# Empty .env file" > .env
          echo "Created .env from Secret Manager or as empty file"
        else
          echo "# Empty .env file" > .env
          echo "Created empty .env file"
        fi
        ls -la
  
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'PORT=$_PORT',
        '--build-arg',
        'ENV=$_ENV',
        '-t',
        'gcr.io/gateway-dashboard-front/battledak-server-$_ENV',
        '.',
      ]
images:
  - 'gcr.io/gateway-dashboard-front/battledak-server-$_ENV'
substitutions:
  _ENV_FILE: '.env'
  _ENV: 'prod'
  _PORT: '8080'
